language: java		
jdk: oraclejdk8

services:
  - mongodb
  - redis-server
  - memcached

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database orbit;' -U postgres

script: "mvn test -P withMongoTests,withPostgresTests,withRedisTests,withMemcachedTests,withScala,withLDAPTests"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/066a8197f92d460e8530
    on_success: always
    on_failure: always  
    on_start: false  
